logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/khub
    username: khub
    password: khub
    driver-class-name: org.postgresql.Driver
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}